###
PUT  http://172.24.152.77:3011/api/v1/users HTTP/1.1
Content-Type: application/json

{  
  "authId": "temp@hello.co.nz",
  "name": "Temp User at Hello co nz"
}

###
PUT  http://172.24.152.77:3011/api/v1/posts HTTP/1.1
Content-Type: application/json
Authorization: 

{  
  "userId": 1,
  "title": "Some tough spiders are thought of simply as figs",
  "content": "Their bird was, in this moment, a silly bear. They were lost without the amicable kiwi that composed their fox. A peach is an amicable crocodile. A tidy fox without sharks is truly a scorpion of willing cats. Shouting with happiness, a currant is a wise currant!"
}

###
GET http://localhost:3011/api/v1/user/fetchbyauthid/temp@hello.co.nz  HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3011/api/v1/user/fetchbyid/1  HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3011/api/v1/posts  HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3011/api/v1/game/complete/26 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3011/health HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3011/api/v1/homepage  HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3011/api/v1/users  HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3011/api/v1/posts2  HTTP/1.1
Content-Type: application/json
