# The new base image to contain runtime dependencies
# Dependencies: Boost >= 1.86

FROM debian:12.11 AS tttsvc_base

RUN apt update -y;  
RUN apt-get remove -y reflex
RUN apt install -y build-essential cmake curl git openssl libssl-dev wget zlib1g-dev libpq-dev python3 python3-pybind11 python3-dev pkg-config;

FROM tttsvc_base AS tttsvc_boost

WORKDIR /usr/src

COPY reflex_linux_amd64.tar.gz /usr/src
RUN tar -xvf reflex_linux_amd64.tar.gz; \
    cp reflex_linux_amd64/reflex /usr/local/bin/reflex
RUN chmod +x /usr/local/bin/reflex

# Install Boost 1.86 or later
COPY boost_1_86_0.tar.gz /usr/src

RUN BOOST_VERSION=1.86.0; \
    BOOST_DIR=boost_1_86_0; \
    tar -xvf boost_1_86_0.tar.gz; \
    cd ${BOOST_DIR}; \
    ./bootstrap.sh --prefix=/usr/local; \
    ./b2 --with-headers --with-system --with-thread --with-date_time --with-regex --with-serialization --with-program_options --with-url install; \
    cd ..; \
    rm -rf ${BOOST_DIR} ${BOOST_DIR}.tar.gz

FROM tttsvc_boost AS tttsvc_builder

WORKDIR /usr/src

EXPOSE 3003

CMD ["reflex", "-r", "(^latest/.*)|^(apiserver/.*\\.(cpp|h)|tttsvc/.*\\.(cpp|h))$|CMakeLists\\.txt", "-s", "--", "sh", "-c", "cmake -DCMAKE_BUILD_TYPE=Release -S. -Bbuild-dev && cmake --build build-dev --target TicTacToeSvc && ./build-dev/tttsvc/TicTacToeSvc --threads 3 --root /usr/src/latest"]
